/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(area-patient)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(available-physicians)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(create-account)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals-2)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals-3)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals-4)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals-5)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(download-pdf)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(success-profile)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(payment)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(area-patient)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(available-physicians)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(create-account)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(define-goals)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(define-goals-2)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(define-goals-3)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(define-goals-4)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(define-goals-5)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(download-pdf)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(success-profile)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(payment)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(area-patient)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(available-physicians)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(create-account)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(define-goals)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(define-goals-2)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(define-goals-3)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(define-goals-4)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(define-goals-5)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(download-pdf)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(login)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(success-profile)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(payment)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(area-patient)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(available-physicians)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(create-account)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals-2)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals-3)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals-4)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(define-goals-5)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(download-pdf)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(success-profile)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(payment)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
